import type { ResumeData, Bullet, VariantSection, WorkSection, Variant } from "../../types/resume"
import { generateId } from "./utils"

type ParseMode = "header" | "variant-section" | "experience" | "education"

/**
 * Parses enriched Markdown (generated by generateMarkdownFromResume) back into ResumeData.
 * Also accepts simple/legacy Markdown without variant markers for backwards compatibility.
 *
 * Enriched format:
 *   ## SectionLabel
 *   ### [Variant Label] {active}   ← named variant, {active} marks the selected one
 *   Content...
 *
 *   ## Experience
 *   ### COMPANY (Dates)
 *   Role
 *   #### intro: [Label] {active}   ← named intro variant
 *   Content...
 *   - [x] Active bullet            ← checkbox syntax for active state
 *   - [ ] Inactive bullet
 *
 * Simple format (backwards compat):
 *   ## Summary
 *   Plain content...               ← single default variant, no headers
 *   - Bullet text                  ← all bullets active
 */
export function parseMarkdownResume(markdown: string): ResumeData {
  const lines = markdown.split("\n").map(l => l.trim())

  const resumeData: ResumeData = {
    name: "Your Name",
    contact: { email: "", links: [] },
    sections: []
  }

  let mode: ParseMode = "header"

  // --- Variant section state ---
  let currentVariantSection: VariantSection | null = null
  let currentVariantId = ""
  let currentVariantLabel = ""
  let currentVariantIsActive = false
  let currentVariantContent: string[] = []

  // --- Work section state ---
  let currentWork: WorkSection | null = null
  let currentIntroVariant: Omit<Variant, "content"> | null = null
  let currentIntroIsActive = false
  let currentIntroContent: string[] = []

  // --- Education lines (simple fallback) ---
  let educationLines: string[] = []

  // ── Flush helpers ─────────────────────────────────────────────────────────

  const flushVariant = () => {
    if (!currentVariantSection || !currentVariantId) return
    const content = currentVariantContent.join(" ").trim()
    const variant: Variant = { id: currentVariantId, label: currentVariantLabel, tags: [], content }
    currentVariantSection.variants.push(variant)
    // Default to first variant; {active} overrides
    if (currentVariantSection.variants.length === 1) {
      currentVariantSection.activeVariantId = variant.id
    }
    if (currentVariantIsActive) {
      currentVariantSection.activeVariantId = variant.id
    }
    currentVariantId = ""
    currentVariantLabel = ""
    currentVariantContent = []
    currentVariantIsActive = false
  }

  const flushVariantSection = () => {
    flushVariant()
    if (currentVariantSection && currentVariantSection.variants.length > 0) {
      resumeData.sections.push(currentVariantSection)
    }
    currentVariantSection = null
  }

  const flushIntroVariant = () => {
    if (!currentWork || !currentIntroVariant) return
    const content = currentIntroContent.join(" ").trim()
    const variant: Variant = { ...currentIntroVariant, content }
    if (!currentWork.intro) {
      currentWork.intro = { label: "Experience Intro", variants: [variant], activeVariantId: variant.id }
    } else {
      currentWork.intro.variants.push(variant)
    }
    if (currentIntroIsActive) {
      currentWork.intro.activeVariantId = variant.id
    }
    currentIntroVariant = null
    currentIntroIsActive = false
    currentIntroContent = []
  }

  const flushWork = () => {
    flushIntroVariant()
    if (currentWork) resumeData.sections.push(currentWork)
    currentWork = null
  }

  // ── Main parse loop ────────────────────────────────────────────────────────

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    // Skip HTML comment blocks
    if (line.startsWith("<!--")) {
      while (i < lines.length && !lines[i].includes("-->")) i++
      continue
    }

    if (!line) continue

    // ── Section boundary detection (## headings) ──────────────────────────
    if (line.match(/^##\s+Summary/i)) {
      flushVariantSection(); flushWork()
      mode = "variant-section"
      currentVariantSection = { type: "variant", id: "summary", label: "Summary", variants: [], activeVariantId: "" }
      continue
    }
    if (line.match(/^##\s+Skills/i)) {
      flushVariantSection(); flushWork()
      mode = "variant-section"
      currentVariantSection = { type: "variant", id: "skills", label: "Skills", sectionHeader: "SKILLS", variants: [], activeVariantId: "" }
      continue
    }
    if (line.match(/^##\s+Experience/i) || line.match(/^##\s+Work/i)) {
      flushVariantSection(); flushWork()
      mode = "experience"
      continue
    }
    if (line.match(/^##\s+Education/i)) {
      flushVariantSection(); flushWork()
      mode = "education"
      educationLines = []
      continue
    }

    // ── Header mode ───────────────────────────────────────────────────────
    if (mode === "header") {
      if (line.startsWith("# ")) {
        resumeData.name = line.replace(/^# /, "").trim()
      } else if (line.toLowerCase().startsWith("email:")) {
        resumeData.contact.email = line.replace(/email:/i, "").trim()
      } else if (line.toLowerCase().startsWith("links:")) {
        const linksStr = line.replace(/links:/i, "").trim()
        linksStr.split(",").map(s => s.trim()).forEach(lp => {
          const mdMatch = lp.match(/\[([^\]]+)\]\(([^)]+)\)/)
          if (mdMatch) { resumeData.contact.links.push({ alias: mdMatch[1].trim(), url: mdMatch[2].trim() }); return }
          const legacyMatch = lp.match(/(.+?)\s*\((.+?)\)/)
          if (legacyMatch) { resumeData.contact.links.push({ alias: legacyMatch[1].trim(), url: legacyMatch[2].trim() }); return }
          if (lp) resumeData.contact.links.push({ alias: lp, url: lp })
        })
      }
      continue
    }

    // ── Variant section mode ──────────────────────────────────────────────
    if (mode === "variant-section" && currentVariantSection) {
      // Enriched: ### [Label] or ### [Label] {active}
      const variantMatch = line.match(/^###\s+\[(.+?)\](\s+\{active\})?$/)
      if (variantMatch) {
        flushVariant()
        currentVariantLabel = variantMatch[1].trim()
        currentVariantId = `${currentVariantSection.id}-${generateId()}`
        currentVariantIsActive = !!variantMatch[2]
        currentVariantContent = []
        continue
      }
      // Content: accumulate into current variant (or start a simple default variant)
      if (currentVariantId) {
        currentVariantContent.push(line)
      } else {
        // Simple format — no variant header, create single default variant
        currentVariantId = `${currentVariantSection.id}-${generateId()}`
        currentVariantLabel = "Default"
        currentVariantIsActive = true
        currentVariantContent = [line]
      }
      continue
    }

    // ── Experience mode ───────────────────────────────────────────────────
    if (mode === "experience") {
      // New work section: ### COMPANY (Dates) or ### COMPANY
      if (line.startsWith("### ")) {
        flushWork()
        const match = line.match(/^###\s+(.+?)(?:\s+\((.+?)\))?$/)
        const company = match ? match[1].trim() : line.replace(/^### /, "").trim()
        const dates = match?.[2]?.trim() ?? ""
        currentWork = { type: "work", id: `work-${generateId()}`, company, role: "", dates, intro: undefined, bullets: [], activeBulletIds: [] }
        continue
      }

      if (!currentWork) continue

      // Enriched intro variant: #### intro: [Label] or #### intro: [Label] {active}
      const introMatch = line.match(/^####\s+intro:\s+\[(.+?)\](\s+\{active\})?$/i)
      if (introMatch) {
        flushIntroVariant()
        currentIntroVariant = { id: `intro-${generateId()}`, label: introMatch[1].trim(), tags: [] }
        currentIntroIsActive = !!introMatch[2]
        currentIntroContent = []
        continue
      }

      // Bullet lines — always end any open intro block first
      if (line.startsWith("- ")) {
        flushIntroVariant()
        const checkboxMatch = line.match(/^- \[(x| )\] (.+)$/)
        if (checkboxMatch) {
          const isActive = checkboxMatch[1] === "x"
          const content = checkboxMatch[2].trim()
          const bullet: Bullet = { id: `bullet-${generateId()}`, label: content.substring(0, 30) + (content.length > 30 ? "..." : ""), tags: [], content }
          currentWork.bullets.push(bullet)
          if (isActive) currentWork.activeBulletIds.push(bullet.id)
        } else {
          // Simple bullet (no checkbox) → active
          const content = line.replace(/^- /, "").trim()
          const bullet: Bullet = { id: `bullet-${generateId()}`, label: content.substring(0, 30) + (content.length > 30 ? "..." : ""), tags: [], content }
          currentWork.bullets.push(bullet)
          currentWork.activeBulletIds.push(bullet.id)
        }
        continue
      }

      // Accumulate open intro block content
      if (currentIntroVariant) {
        currentIntroContent.push(line)
        continue
      }

      // Role (first plain text line after company header)
      if (!currentWork.role) {
        currentWork.role = line
        continue
      }

      // Simple intro (plain text after role, before bullets — no #### intro: marker)
      const introId = `intro-${generateId()}`
      currentIntroVariant = { id: introId, label: "Base Intro", tags: ["base"] }
      currentIntroIsActive = true
      currentIntroContent = [line]
      continue
    }

    // ── Education mode ────────────────────────────────────────────────────
    if (mode === "education") {
      // Enriched: ### [Label] or ### [Label] {active} — treat as variant section
      const variantMatch = line.match(/^###\s+\[(.+?)\](\s+\{active\})?$/)
      if (variantMatch) {
        if (!currentVariantSection) {
          currentVariantSection = { type: "variant", id: "education", label: "Education", sectionHeader: "EDUCATION", variants: [], activeVariantId: "" }
          mode = "variant-section"
        }
        flushVariant()
        currentVariantLabel = variantMatch[1].trim()
        currentVariantId = `education-${generateId()}`
        currentVariantIsActive = !!variantMatch[2]
        currentVariantContent = []
        continue
      }
      // Simple education: accumulate lines (degree / institution / location)
      educationLines.push(line)
    }
  }

  // ── Flush remaining state ─────────────────────────────────────────────────
  flushVariantSection()
  flushWork()

  // Build education from simple lines if not already added as a VariantSection
  const hasEducationSection = resumeData.sections.some(s => s.id === "education")
  if (!hasEducationSection && educationLines.length > 0) {
    const content = educationLines.join(" — ")
    const eduId = `edu-${generateId()}`
    resumeData.sections.push({
      type: "variant",
      id: "education",
      label: "Education",
      sectionHeader: "EDUCATION",
      variants: [{ id: eduId, label: "Education", tags: [], content }],
      activeVariantId: eduId
    })
  }

  // ── Validate bare minimums ────────────────────────────────────────────────
  if (!resumeData.name.trim() || resumeData.name === "Your Name") {
    throw new Error("Invalid resume template: must include a # Name header.")
  }
  if (resumeData.sections.length === 0) {
    throw new Error("Invalid resume template: must include at least one ## section.")
  }

  return resumeData
}
